// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: TempMonitor.proto
#ifndef GRPC_TempMonitor_2eproto__INCLUDED
#define GRPC_TempMonitor_2eproto__INCLUDED

#include "TempMonitor.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace TempMonitorSink {

// The greeting service definition.
class TempMonitorServer final {
 public:
  static constexpr char const* service_full_name() {
    return "TempMonitorSink.TempMonitorServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::TempMonitorSink::empty_param* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempMonitorSink::empty_param>> AsyncUpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempMonitorSink::empty_param>>(AsyncUpdateSubSystemTempRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempMonitorSink::empty_param>> PrepareAsyncUpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TempMonitorSink::empty_param>>(PrepareAsyncUpdateSubSystemTempRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TempMonitorSink::empty_param* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TempMonitorSink::empty_param* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TempMonitorSink::empty_param>* AsyncUpdateSubSystemTempRaw(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TempMonitorSink::empty_param>* PrepareAsyncUpdateSubSystemTempRaw(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::TempMonitorSink::empty_param* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>> AsyncUpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>>(AsyncUpdateSubSystemTempRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>> PrepareAsyncUpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>>(PrepareAsyncUpdateSubSystemTempRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response, std::function<void(::grpc::Status)>) override;
      void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TempMonitorSink::empty_param* response, std::function<void(::grpc::Status)>) override;
      void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void UpdateSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TempMonitorSink::empty_param* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>* AsyncUpdateSubSystemTempRaw(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>* PrepareAsyncUpdateSubSystemTempRaw(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateSubSystemTemp_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_UpdateSubSystemTemp() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateSubSystemTemp(::grpc::ServerContext* context, ::TempMonitorSink::SubSysIdAndTemp* request, ::grpc::ServerAsyncResponseWriter< ::TempMonitorSink::empty_param>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateSubSystemTemp<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_UpdateSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_UpdateSubSystemTemp() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::TempMonitorSink::SubSysIdAndTemp, ::TempMonitorSink::empty_param>(
          [this](::grpc::ServerContext* context,
                 const ::TempMonitorSink::SubSysIdAndTemp* request,
                 ::TempMonitorSink::empty_param* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->UpdateSubSystemTemp(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_UpdateSubSystemTemp(
        ::grpc::experimental::MessageAllocator< ::TempMonitorSink::SubSysIdAndTemp, ::TempMonitorSink::empty_param>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TempMonitorSink::SubSysIdAndTemp, ::TempMonitorSink::empty_param>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_UpdateSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_UpdateSubSystemTemp<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdateSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_UpdateSubSystemTemp() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_UpdateSubSystemTemp() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdateSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateSubSystemTemp(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_UpdateSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_UpdateSubSystemTemp() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->UpdateSubSystemTemp(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_UpdateSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void UpdateSubSystemTemp(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_UpdateSubSystemTemp() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::TempMonitorSink::SubSysIdAndTemp, ::TempMonitorSink::empty_param>(std::bind(&WithStreamedUnaryMethod_UpdateSubSystemTemp<BaseClass>::StreamedUpdateSubSystemTemp, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_UpdateSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateSubSystemTemp(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TempMonitorSink::SubSysIdAndTemp,::TempMonitorSink::empty_param>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateSubSystemTemp<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateSubSystemTemp<Service > StreamedService;
};

}  // namespace TempMonitorSink


#endif  // GRPC_TempMonitor_2eproto__INCLUDED
