// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempMonitor.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TempMonitor_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TempMonitor_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TempMonitor_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TempMonitor_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TempMonitor_2eproto;
namespace TempMonitorSink {
class SubSysIdAndTemp;
class SubSysIdAndTempDefaultTypeInternal;
extern SubSysIdAndTempDefaultTypeInternal _SubSysIdAndTemp_default_instance_;
class empty_param;
class empty_paramDefaultTypeInternal;
extern empty_paramDefaultTypeInternal _empty_param_default_instance_;
}  // namespace TempMonitorSink
PROTOBUF_NAMESPACE_OPEN
template<> ::TempMonitorSink::SubSysIdAndTemp* Arena::CreateMaybeMessage<::TempMonitorSink::SubSysIdAndTemp>(Arena*);
template<> ::TempMonitorSink::empty_param* Arena::CreateMaybeMessage<::TempMonitorSink::empty_param>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace TempMonitorSink {

// ===================================================================

class empty_param :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TempMonitorSink.empty_param) */ {
 public:
  empty_param();
  virtual ~empty_param();

  empty_param(const empty_param& from);
  empty_param(empty_param&& from) noexcept
    : empty_param() {
    *this = ::std::move(from);
  }

  inline empty_param& operator=(const empty_param& from) {
    CopyFrom(from);
    return *this;
  }
  inline empty_param& operator=(empty_param&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const empty_param& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const empty_param* internal_default_instance() {
    return reinterpret_cast<const empty_param*>(
               &_empty_param_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(empty_param* other);
  friend void swap(empty_param& a, empty_param& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline empty_param* New() const final {
    return CreateMaybeMessage<empty_param>(nullptr);
  }

  empty_param* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<empty_param>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const empty_param& from);
  void MergeFrom(const empty_param& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(empty_param* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TempMonitorSink.empty_param";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_TempMonitor_2eproto);
    return ::descriptor_table_TempMonitor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:TempMonitorSink.empty_param)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TempMonitor_2eproto;
};
// -------------------------------------------------------------------

class SubSysIdAndTemp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TempMonitorSink.SubSysIdAndTemp) */ {
 public:
  SubSysIdAndTemp();
  virtual ~SubSysIdAndTemp();

  SubSysIdAndTemp(const SubSysIdAndTemp& from);
  SubSysIdAndTemp(SubSysIdAndTemp&& from) noexcept
    : SubSysIdAndTemp() {
    *this = ::std::move(from);
  }

  inline SubSysIdAndTemp& operator=(const SubSysIdAndTemp& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubSysIdAndTemp& operator=(SubSysIdAndTemp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SubSysIdAndTemp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SubSysIdAndTemp* internal_default_instance() {
    return reinterpret_cast<const SubSysIdAndTemp*>(
               &_SubSysIdAndTemp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SubSysIdAndTemp* other);
  friend void swap(SubSysIdAndTemp& a, SubSysIdAndTemp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SubSysIdAndTemp* New() const final {
    return CreateMaybeMessage<SubSysIdAndTemp>(nullptr);
  }

  SubSysIdAndTemp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SubSysIdAndTemp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SubSysIdAndTemp& from);
  void MergeFrom(const SubSysIdAndTemp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubSysIdAndTemp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TempMonitorSink.SubSysIdAndTemp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_TempMonitor_2eproto);
    return ::descriptor_table_TempMonitor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 SubSysId = 1;
  void clear_subsysid();
  static const int kSubSysIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 subsysid() const;
  void set_subsysid(::PROTOBUF_NAMESPACE_ID::int32 value);

  // float Temp = 2;
  void clear_temp();
  static const int kTempFieldNumber = 2;
  float temp() const;
  void set_temp(float value);

  // @@protoc_insertion_point(class_scope:TempMonitorSink.SubSysIdAndTemp)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 subsysid_;
  float temp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TempMonitor_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// empty_param

// -------------------------------------------------------------------

// SubSysIdAndTemp

// int32 SubSysId = 1;
inline void SubSysIdAndTemp::clear_subsysid() {
  subsysid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SubSysIdAndTemp::subsysid() const {
  // @@protoc_insertion_point(field_get:TempMonitorSink.SubSysIdAndTemp.SubSysId)
  return subsysid_;
}
inline void SubSysIdAndTemp::set_subsysid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  subsysid_ = value;
  // @@protoc_insertion_point(field_set:TempMonitorSink.SubSysIdAndTemp.SubSysId)
}

// float Temp = 2;
inline void SubSysIdAndTemp::clear_temp() {
  temp_ = 0;
}
inline float SubSysIdAndTemp::temp() const {
  // @@protoc_insertion_point(field_get:TempMonitorSink.SubSysIdAndTemp.Temp)
  return temp_;
}
inline void SubSysIdAndTemp::set_temp(float value) {
  
  temp_ = value;
  // @@protoc_insertion_point(field_set:TempMonitorSink.SubSysIdAndTemp.Temp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace TempMonitorSink

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TempMonitor_2eproto
