// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: TempMonitor.proto

#include "TempMonitor.pb.h"
#include "TempMonitor.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace TempMonitorSink {

static const char* TempMonitorServer_method_names[] = {
  "/TempMonitorSink.TempMonitorServer/UpdateSubSystemTemp",
};

std::unique_ptr< TempMonitorServer::Stub> TempMonitorServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TempMonitorServer::Stub> stub(new TempMonitorServer::Stub(channel));
  return stub;
}

TempMonitorServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_UpdateSubSystemTemp_(TempMonitorServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TempMonitorServer::Stub::UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::TempMonitorSink::empty_param* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UpdateSubSystemTemp_, context, request, response);
}

void TempMonitorServer::Stub::experimental_async::UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateSubSystemTemp_, context, request, response, std::move(f));
}

void TempMonitorServer::Stub::experimental_async::UpdateSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TempMonitorSink::empty_param* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UpdateSubSystemTemp_, context, request, response, std::move(f));
}

void TempMonitorServer::Stub::experimental_async::UpdateSubSystemTemp(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateSubSystemTemp_, context, request, response, reactor);
}

void TempMonitorServer::Stub::experimental_async::UpdateSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TempMonitorSink::empty_param* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UpdateSubSystemTemp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>* TempMonitorServer::Stub::AsyncUpdateSubSystemTempRaw(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::TempMonitorSink::empty_param>::Create(channel_.get(), cq, rpcmethod_UpdateSubSystemTemp_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::TempMonitorSink::empty_param>* TempMonitorServer::Stub::PrepareAsyncUpdateSubSystemTempRaw(::grpc::ClientContext* context, const ::TempMonitorSink::SubSysIdAndTemp& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::TempMonitorSink::empty_param>::Create(channel_.get(), cq, rpcmethod_UpdateSubSystemTemp_, context, request, false);
}

TempMonitorServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TempMonitorServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TempMonitorServer::Service, ::TempMonitorSink::SubSysIdAndTemp, ::TempMonitorSink::empty_param>(
          std::mem_fn(&TempMonitorServer::Service::UpdateSubSystemTemp), this)));
}

TempMonitorServer::Service::~Service() {
}

::grpc::Status TempMonitorServer::Service::UpdateSubSystemTemp(::grpc::ServerContext* context, const ::TempMonitorSink::SubSysIdAndTemp* request, ::TempMonitorSink::empty_param* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace TempMonitorSink

